README: fix docker image instructions
Two issues are fixed:

 - Initial `docker build` instructions fail because the Dockerfile path
   is wrong (elixir/Dockerfile versus elixir/docker/Dockerfile).

 - Indexing instructions are wrong because they do not use the
   virtualenv Python. It contains the installed packages, which we need
   for indexing. Issue appears as:

      ModuleNotFoundError: No module named 'bsddb3' (edited)

We also remove some common Docker knowledge (why we might want the
database to be coming from a mounted volume, rather than stored inside
the container).

Finally, we fix line widths but splitting commands into multiple lines.

Signed-off-by: Théo Lebrun <theo.lebrun@bootlin.com>